name: Video Auto Convert
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Install yt-dlp & FFmpeg
        run: |
          sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          sudo apt update && sudo apt install ffmpeg -y
      
      - name: Download and Convert to MP4
        run: |
          # سيقوم بالتحميل والدمج في صيغة mp4 مباشرة باستخدام سيرفرات جيت هاب
          yt-dlp -f "bv*[height<=2160]+ba/b" \
          --download-sections "*00:00:00-01:00:00" \
          --merge-output-format mp4 \
          "https://www.youtube.com/watch?v=g6Ye4xwXyAw" \
          -o "fireplace_4k.mp4"
          
      - name: Upload to Transfer.sh
        run: |
          # هذا السطر سيرفع الملف ويعطيك رابط تحميل مباشر في سجلات العمل (Logs)
          curl --upload-file ./fireplace_4k.mp4 https://transfer.sh/fireplace_4k.mp4 > download_link.txt
          echo "رابط التحميل المباشر هو:"
          cat download_link.txt
